language: "ko-KR"

reviews:
  profile: "chill"
  auto_review:
    enabled: true
    base_branches: ["main", "dev"]
  path_instructions:
    - path: "src/components/**/*.tsx"
      instructions: |
        - 컴포넌트명은 PascalCase를 따르는지 확인.
        - 함수형 컴포넌트와 hooks 패턴 사용 권장.
        - props에 대한 타입(interface 또는 type)이 명시되어 있는지 확인.
        - 리스트 렌더링 시 안정적인 key prop 사용 여부 확인 (index 사용 지양).
        - 큰 컴포넌트는 적절히 분리되어 있는지 검토 (단일 책임 원칙).
        - 불필요한 리렌더링을 유발하는 패턴이 있는지 확인 (인라인 객체/함수 생성, 불필요한 state 등).
        - Tailwind 클래스는 논리적 순서로 작성 (레이아웃 → 간격 → 색상).

    - path: "src/app/**/*.tsx"
      instructions: |
        - Next.js App Router 컨벤션 준수 (Server/Client 컴포넌트 구분).
        - "use client" 지시어가 정말 필요한 경우에만 사용되고 있는지 검토.
        - 데이터 페칭이 필요한 경우 서버 컴포넌트 활용을 우선 고려.
        - 인라인 스타일 대신 Tailwind 유틸리티 사용.
        - useEffect 내부에서 데이터 페칭하는 대신 React Query 훅 사용 권장.

    - path: "src/app/**/hooks/**/*.ts"
      instructions: |
        - 훅 이름은 use 접두사를 따르는지 확인.
        - useEffect, useMemo, useCallback의 의존성 배열이 정확한지 검토.
        - useEffect에 필요한 cleanup 함수가 누락되지 않았는지 확인 (타이머, 이벤트 리스너, 구독 등).
        - 하나의 훅이 너무 많은 책임을 가지고 있지 않은지 검토.

    - path: "src/hooks/**/*.ts"
      instructions: |
        - 훅 이름은 use 접두사를 따르는지 확인.
        - useEffect, useMemo, useCallback의 의존성 배열이 정확한지 검토.
        - useEffect에 필요한 cleanup 함수가 누락되지 않았는지 확인 (타이머, 이벤트 리스너, 구독 등).
        - 하나의 훅이 너무 많은 책임을 가지고 있지 않은지 검토.

    - path: "src/queries/**/*.ts"
      instructions: |
        - queryKey가 일관된 패턴으로 정의되어 있는지 확인.
        - staleTime, gcTime 등 캐싱 옵션이 적절하게 설정되어 있는지 검토.
        - useMutation 성공 시 관련 쿼리 캐시 무효화(invalidateQueries)가 누락되지 않았는지 확인.
        - 에러 핸들링이 적절히 처리되고 있는지 검토.

    - path: "src/api/**/*.ts"
      instructions: |
        - API 함수가 단일 책임 원칙을 따르는지 확인.
        - 요청/응답에 대한 타입이 명시되어 있는지 검토.
        - 에러 핸들링이 일관된 패턴으로 처리되고 있는지 확인.

    - path: "src/types/**/*.ts"
      instructions: |
        - any 타입 사용을 최소화하고 있는지 확인.
        - 타입/인터페이스 네이밍이 명확한지 검토.
        - 중복된 타입 정의가 없는지 확인.

    - path: "src/utils/**/*.ts"
      instructions: |
        - 유틸리티 함수가 순수 함수로 작성되어 있는지 확인.
        - 사이드 이펙트가 최소화되어 있는지 검토.

    - path: "src/lib/**/*.ts"
      instructions: |
        - Zod 스키마 사용 시 검증 로직이 명확하고 재사용 가능한지 확인.
        - 외부 라이브러리 초기화 코드가 안전하게 작성되어 있는지 검토.
